name = "stok-skt-cari-takip"
main = "worker.js"
compatibility_date = "2026-08-13"

[[database_id = "7e804db3-7b00-461b-9094-5fd7348c4029"]]
binding = "DB"
database_name = "stok-skt-cari-takip"
database_id = "BURAYA_D1_DATABASE_ID"
