name = "stok-skt-cari-takip"
main = "worker.js"
compatibility_date = "2026-08-13"

[[d1_databases]]
binding = "DB"
database_name = "stok-skt-cari-takip"
database_id = "7e804db3-7b00-461b-9094-5fd7348c4029"
